export const widgetLabels: Record<string, string> = {
  solarPower: "Solar power",
  fuelCellPower: "Ene-Farm power",
  branchDemandPower: "Circuits total",
  batteryPower: "Battery power",
  batterySoc: "Battery state of charge",
  gridImportPower: "Grid import",
  gridExportPower: "Grid export",
  adaptiveCharging: "Adaptive charging",
  backupPreparation: "Disaster prep",
  awayStatus: "Away status",
  batteryWorking: "Battery working state",
  operationMode: "Battery operation mode",
  vendorProfile: "Battery profile",
  dischargeLimit: "Battery reserve",
  fuelCellStatus: "Ene-Farm status",
  fuelCellStateTimeline: "Ene-Farm activity",
  fuelCellHotWater: "Ene-Farm hot water",
  solarSavings: "Solar savings",
  co2Savings: "Avoided CO₂",
  offPeakSavings: "Off-peak savings",
  powerImported: "Imported energy",
  powerExported: "Exported energy",
  guardTriggerCount: "Demand Guard triggers",
  energySources: "Energy sources",
};
